### PR TITLE
Add Minitest 5 compatibility

### PR DESCRIPTION
**Pull request by rmm5t**
(title)

### CODE REVIEW

**Comment by rmm5t** [comment]
@frodsan A friend of mine contacted me lamenting about lack of minitest 5 support in [mongoid-minitest](https://github.com/frodsan/mongoid-minitest).

I'm in the process of updating both minitest-activemodel and mongoid-minitest to bring them both up to snuff with the latest dependencies. Going to try to get everything fully green against a decent build matrix beforehand too.

As a heads-up, we're going to need some new (semver) versions after all this, but I'm happy to take the lead there if you want to give me rubygems push credentials for both projects.

**Comment by rmm5t** [comment]
Oh, @frodsan, my rubygems email address is listed on my [github profile](https://github.com/rmm5t).

http://stackoverflow.com/a/8487747/8985

**Comment by rmm5t** [comment]
@frodsan Ready for a `rake release` too. See 769338f7410d109474d3b19e79e66ff7033c1656

**Comment by frodsan** [comment]
@rmm5t You are more than welcome to take the lead. I'm not using Rails for a while. Thanks!!! :tada: :+1: 

I will add you to rubygems.

**Comment by frodsan** [comment]
1.1.0 is released https://rubygems.org/gems/minitest-activemodel

**Comment by rmm5t** [comment]
Thanks @frodsan!

**Pull request merged**
